import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderFinal from "@/components/headFoot/HeaderFinal";
import Footer from "@/components/headFoot/Footer";
import StickyWrapper from "@/components/STICKY/StickyWrapper";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RedButton",
  description: "Generated by create next app",
};
export const viewport: Viewport = { width: "device-width", initialScale: 1 };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderFinal />
        <StickyWrapper />
        {children}
        <Footer />
      </body>
    </html>
  );
}
